# Generated by Django 5.2.4 on 2025-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=50)),
                ('main_actors', models.CharField(max_length=200)),
                ('running_time', models.IntegerField()),
                ('review_content', models.TextField()),
            ],
        ),
    ]
