# Generated by Django 5.2.4 on 2025-07-11 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review_content',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='unknown', max_length=100, verbose_name='배우'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='포스터 URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(default='unknown', verbose_name='리뷰'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=2000, verbose_name='개봉년도'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.PositiveIntegerField(default=0, verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
