# Generated by Django 5.2.4 on 2025-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_main_actors_remove_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='입력해주세요!', max_length=100, verbose_name='배우'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Animation', 'Animation')], max_length=30, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(default='입력해주세요!', verbose_name='리뷰'),
        ),
    ]
